name = "icon-anvilcraft-dev"
main = "src/index.ts"
compatibility_date = "2025-06-01"

# Import the SVG badge templates as text modules.
rules = [{ type = "Text", globs = ["**/*.svg"], fallthrough = true }]

# Custom domain. Make sure the DNS of icon.anvilcraft.dev is managed by Cloudflare.
routes = [{ pattern = "*/*", zone_name = "modwiki.dev" }]

# KV cache namespace. Replace `id` with the output of:
#   npx wrangler kv namespace create ICON_CACHE
[[kv_namespaces]]
binding = "ICON_CACHE"
id = "33569436b9b44abeb46263851669af1d"
